// src/components/Alert.jsx
const typeStyles = {
  primary: 'bg-[#CCE5FF] border-[#B8DAFF] text-[#004085]',
  warning: 'bg-[#FFF3CD] border-[#FFEEBA] text-[#856404]',
  success: 'bg-[#D4EDDA] border-[#C3E6CB] text-[#155724]',
  info: 'bg-[#d1ecf1] border-[#bee5eb] text-[#0c5460]',
  danger: 'bg-[#f8d7da] border-[#f5c6cb] text-[#721c24]',
};

export default function Alert({ type, children }) {
  return (
    <div
      className={`rounded-[10px] border p-4 text-center text-base font-normal min-[450px]:text-[1.2rem] [&_a]:text-inherit [&_a]:underline ${typeStyles[type] || ''}`}
    >
      {children}
    </div>
  );
}

// src/components/Alert.vue
<template>
  <div class="base" :class="type">
      <slot></slot>
  </div>
</template>

<script>
export default {
    props: {
        type: String
    }
}
</script>

<style scoped>
    .base {
        padding: 1rem;
        font-size: 1.2rem;
        font-weight: 400;
        text-align: center;
        border-radius: 10px;
    }
    .primary {
        background: #CCE5FF;
        border: 1px solid #B8DAFF;
        color: #004085;
    }
    .warning {
        background: #FFF3CD;
        border: 1px solid #FFEEBA;
        color: #856404;
    }
    .success {
        background: #D4EDDA;
        border: 1px solid #C3E6CB;
        color: #155724;
    }
    .info {
        color: #0c5460;
        background-color: #d1ecf1;
        border-color: #bee5eb;
    }
    .danger {
        color: #721c24;
        background-color: #f8d7da;
        border-color: #f5c6cb;
    }

    @media (max-width: 450px) {
        .base {
            font-size: 1rem;
        }
    }
</style>
