// src/components/Banner.jsx
import Image from 'next/image';

export default function Banner({ title, subTitle, image, imageAlt }) {
  return (
    <div className="flex flex-col-reverse items-center min-[768px]:flex-row min-[768px]:items-end">
      <div className="flex-1 text-center min-[768px]:text-left">
        <h1 className="text-[2.2rem] font-light min-[450px]:text-[3.5rem] min-[600px]:text-[4rem]">
          {title}
        </h1>
        <p className="text-[1.2rem] font-medium text-[#999] min-[450px]:text-[1.7rem] min-[600px]:text-[2.2rem]">
          {subTitle}
        </p>
      </div>
      {image && (
        <Image
          src={image}
          alt={imageAlt || ''}
          width={520}
          height={520}
          priority
          className="w-[22rem] min-[450px]:w-[26rem]"
        />
      )}
    </div>
  );
}

// src/components/Banner.vue
<template>
  <div class="banner">
      <div class="text-section">
          <div class="banner-title">{{title}}</div>
          <div class="banner-sub-title">{{subTitle}}</div>
      </div>
      <slot name="image"></slot>
  </div>
</template>

<script>
export default {
    props: {
        image: String,
        title: String,
        subTitle: String
    }
}
</script>

<style scoped>
    .banner {
        display: flex;
        align-items: flex-end;
        /* border: 1px solid; */
    }

    .text-section {
        flex: 1;
    }

    .banner-title {
        font-size: 4rem;
        font-weight: 300;
    }

    .banner-sub-title {
        color: #999;
        font-weight: 500;
        font-size: 2.2rem;
    }

    @media (max-width: 768px) {
        .banner {
            flex-direction: column-reverse;
            align-items: center;
        }
        .text-section {
            text-align: center;
        }
    }

    @media (max-width: 600px) {
        .banner-title {
            font-size: 3.5rem;
        }

        .banner-sub-title {
            color: #999;
            font-weight: 500;
            font-size: 1.7rem;
        }
    }

    @media (max-width: 450px) {
        .banner-title {
            font-size: 2.2rem;
        }

        .banner-sub-title {
            color: #999;
            font-weight: 500;
            font-size: 1.2rem;
        }
    }
</style>
